apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.app.app_label }}
  selector:
    app: {{ .Values.app.app_label }}
  ports:
    - protocol: {{ .Values.app.service.protocol }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.deployment.applicationPort }} 
      nodePort: {{ .Values.app.service.nodePort }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.namespace }} 
  labels:
    app: {{ .Values.app.app_label }}
spec:
  replicas: {{ .Values.app.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.app_label }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.app_label }}
    spec:
      containers:
      - name: {{ .Values.app.name }}-app
        image: {{ .Values.app.deployment.containerImageName }}:{{ .Values.app.deployment.containerImageTag }}
        env:
          - name: MYSQL_URL
            value: jdbc:mysql://{{ .Values.app.deployment.databaseUrl }}/{{ .Values.app.name }}
          - name: PORT
            value: {{ .Values.app.deployment.applicationPort }}
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.secret.name }} 
                key: MYSQL_USER
          - name: MYSQL_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.db.secret.name }}
                key: MYSQL_PASS
        ports:
        - containerPort: {{ .Values.app.deployment.applicationPort }}
      imagePullSecrets:
      - name: {{ .Values.app.deployment.registrySecretName }}
